import hashlib
import math
import re

from app.services.llm.base import BaseLLMProvider, LLMMessage


class LocalFallbackProvider(BaseLLMProvider):
    async def chat(self, messages: list[LLMMessage], temperature: float = 0.2) -> str:
        return messages[-1].content if messages else ""

    async def structured_output(self, system_prompt: str, user_prompt: str, schema: dict) -> dict:
        words = sorted(set(re.findall(r"[A-Za-z][A-Za-z0-9+#.-]{1,}", user_prompt)))
        return {
            "summary": user_prompt[:500],
            "keywords": words[:40],
            "note": "Generated by local fallback because no configured LLM API key was available.",
        }

    async def embedding(self, text: str) -> list[float]:
        vector = [0.0] * 384
        tokens = re.findall(r"[A-Za-z0-9+#.-]+", text.lower())
        for token in tokens:
            digest = hashlib.sha256(token.encode("utf-8")).digest()
            index = int.from_bytes(digest[:2], "big") % len(vector)
            sign = 1 if digest[2] % 2 == 0 else -1
            vector[index] += sign
        norm = math.sqrt(sum(value * value for value in vector)) or 1.0
        return [value / norm for value in vector]

